{
	"posts_num":"9",
	"posts":[
		{"postID":"12",
			"author":"1",
			"content":"12",
			"postTitle":"1",
			"bookTitle":"12",
			"publisher":"1",
			"time":"1",
			"cover":"《職場悠遊卡》是現代上班族絕對必備的辦公室生存手冊。尤其是經濟不景氣，失業率節節高升的當下，上班族更需要穿戴鋼盔鐵甲，好好地捍衛住自己的疆土。辦公室是一個看似和平寧靜，其實暗藏詭譎的戰場，人人都想成功，但如何才能成功？在追求成功的過程中又該如何經營良好的同儕關係？如何與老闆、主管相處？遭到排擠、忌妒或流言中傷時又該怎麼辦......？<br/><br/>本書所談的每一個問題，都是我們俯拾皆是的工作難題，作者以她豐富的職場經驗，教我們「以智取不以力取」，透過她入情入理的剖析，深入淺出的陳述，尋找可聽、可行的解決妙方。",
			"publisherName":"1",
			"commentNum":"1"},
		{"postID":"12","author":"1",
				"content":"12","postTitle":"1",
				"bookTitle":"12","publisher":"1",
				"time":"1","cover":"1","publisherName":"1","commentNum":"1"},
		{"postID":"12","author":"1","content":"12111111111111111111111111111111111111111111111111","postTitle":"1","bookTitle":"12","publisher":"1","time":"1","cover":"1","publisherName":"1","commentNum":"1"},
		{"postID":"12","author":"1","content":"12","postTitle":"1","bookTitle":"12","publisher":"1","time":"1","cover":"1","publisherName":"1","commentNum":"1"},
		{"postID":"12","author":"1","content":"12","postTitle":"1","bookTitle":"12","publisher":"1","time":"1","cover":"1","publisherName":"1","commentNum":"1"},
		{"postID":"12","author":"1","content":"12","postTitle":"1","bookTitle":"12","publisher":"1","time":"1","cover":"1","publisherName":"1","commentNum":"1"},
		{"postID":"12","author":"1","content":"12","postTitle":"1","bookTitle":"12","publisher":"1","time":"1","cover":"1","publisherName":"1","commentNum":"1"},
		{"postID":"12","author":"1","content":"12","postTitle":"1","bookTitle":"12","publisher":"1","time":"1","cover":"1","publisherName":"1","commentNum":"1"},
		{"postID":"12","author":"1","content":"12","postTitle":"1","bookTitle":"12","publisher":"1","time":"1","cover":"1","publisherName":"1","commentNum":"1"}
	],
"comment_num":"9",
"comments":[
	{"postID":"12","commentID":"1","time":"12","content":"111111111111111111111111111111111111111111111","commentParentContent":"12","commentParentPublisher":"1"},
	{"postID":"12","commentID":"1","time":"12","content":"1","commentParentContent":"12","commentParentPublisher":"1"},
	{"postID":"12","commentID":"1","time":"12","content":"1","commentParentContent":"12","commentParentPublisher":"1"},
	{"postID":"12","commentID":"1","time":"12","content":"1","commentParentContent":"12","commentParentPublisher":"1"},
	{"postID":"12","commentID":"1","time":"12","content":"1","commentParentContent":"12","commentParentPublisher":"1"},
	{"postID":"12","commentID":"1","time":"12","content":"1","commentParentContent":"12","commentParentPublisher":"1"},
	{"postID":"12","commentID":"1","time":"12","content":"1","commentParentContent":"12","commentParentPublisher":"1"},
	{"postID":"12","commentID":"1","time":"12","content":"1","commentParentContent":"12","commentParentPublisher":"1"},
	{"postID":"12","commentID":"1","time":"12","content":"1","commentParentContent":"12","commentParentPublisher":"1"}
	],
"following_num":"1",
"followings":[
              {"userID":"1","icon":"img/flo1.jpg","userName":"123"},
              {"userID":"1","icon":"img/flo1.jpg","userName":"123"},
              {"userID":"1","icon":"img/flo1.jpg","userName":"123"},
              {"userID":"1","icon":"img/flo1.jpg","userName":"123"},
              {"userID":"1","icon":"img/flo1.jpg","userName":"123"},
              {"userID":"1","icon":"img/flo1.jpg","userName":"123"}
              ]
	

}